### ISSUE TITLE
Could you explain how metrics like Maj@8 and RM@8 are obtained?

### ISSUE THREAD

**Issue by kresle** [QwenLM/Qwen2.5-Math#12]
The current description merely mentions them without any explanation, and there is almost no relevant content available online.
Thanks~

**Comment by liudayiheng** [comment]
Maj@8: random sample  8 response for major voting (Choose the answer with the highest frequency among the 8 as the final answer).

Maj@8: random sample  8 response and choose the one with the highest RM score among the 8 as the final answer.

**Comment by haoxiongliu** [comment]
> Maj@8: random sample 8 responses for major voting (Choose the answer with the highest frequency among the 8 as the final answer).
> 
> Maj@8: random sample 8 responses and choose the one with the highest RM score among the 8 as the final answer.

What is the temperature used in these tests?

**Comment by ToheartZhang** [comment]
> > Maj@8: random sample 8 responses for major voting (Choose the answer with the highest frequency among the 8 as the final answer).
> > Maj@8: random sample 8 responses and choose the one with the highest RM score among the 8 as the final answer.
> 
> What is the temperature used in these tests?

temperature=0.7, top_p=0.8
