### ISSUE TITLE
有没有Qwen2.5-Math-RM-72B的调用说明

### ISSUE THREAD

**Issue by CHNZYX** [QwenLM/Qwen2.5-Math#18]
本地部署Reward Model后，模型会在回答中重复一遍问题，然后生成一些混乱内容。是否需要特定prompt才能获得正常回答？

**Comment by zhenruzhang** [comment]
Reward Model主要用于打分而非生成，具体的使用说明可以看huggingface modelcard中的样例

**Comment by CHNZYX** [comment]
看到了，感谢
