### ISSUE TITLE
亲测”prompt前后去掉空格“对解题结果的影响很大，这个是为什么？如何解释？

### ISSUE THREAD

**Issue by a-bean-sprout** [QwenLM/Qwen2.5-Math#20]
prompt前后去掉空格的代码。

https://github.com/QwenLM/Qwen2.5-Math/blob/e128aa06871c7a0eeedc2ab21b69459bcb24c4fb/evaluation/utils.py#L240

**Comment by ToheartZhang** [comment]
因为如果prompt结尾有空格，会导致模型的分词和正常训练时不同，因此建议去掉prompt结尾的空格。类似情况可见https://www.reddit.com/r/GPT3/comments/ssiru2/text_ends_in_a_trailing_space/
