### ISSUE TITLE
关于qwen-2.5-math-7B-instruct的结果复现

### ISSUE THREAD

**Issue by 1245244103** [QwenLM/Qwen2.5-Math#21]
我使用默认参数评测GSM8K数据集，qwen-2.5-math-7B的结果是92.8，而report结果是94.6，MATH数据集上也差大概2个点，是正常波动，还是有什么参数需要更改，或者有什么后处理吗

**Comment by ToheartZhang** [comment]
Please check whether the model weights are the newest version in Huggingface.
