### ISSUE TITLE
Hyperparameters for sampling. 

### ISSUE THREAD

**Issue by PINE4PPLE** [QwenLM/Qwen2.5-Math#22]
Could you share the hyperparameters for sampling in maj@8 and RM@8. When I used temperature as 1 and 0.7, Qwen-2.5-Math-7B-Instruct would sometimes generate non-sense texts. Is this a normal phenomenon or is there some specific hyperparameters required？

**Comment by ToheartZhang** [comment]
Please set temperature=0.7, top_p=0.8.
