### ISSUE TITLE
请问olympiad这个任务的prompt有单独构造吗？

### ISSUE THREAD

**Issue by Violettttee** [QwenLM/Qwen2.5-Math#28]
请问olympiad这个任务的prompt有单独构造吗？看了下evaluate.py和parser里面是有olympiad任务，但是math_eval和调用的数据集里面都没olympiad的判断，utils.py里的examples也没有olympiad。我之前看原本的olympiadbench里面是有单独拼promot的，但是目前没找到该项目的promot拼接。

**Comment by ToheartZhang** [comment]
没有单独构造olympiad的prompt，该数据集基于0 shot评测，所以examples里没有olympiad。

**Comment by Violettttee** [comment]
> 没有单独构造olympiad的prompt，该数据集基于0 shot评测，所以examples里没有olympiad。

明白～还有个问题想请教一下，我看prompt type有cot和qwen25-math-cot，但debug的时候并没有看到对qwen25-math-cot做额外的条件判断之类的，这两个有什么区别吗？

**Comment by ToheartZhang** [comment]
> > 没有单独构造olympiad的prompt，该数据集基于0 shot评测，所以examples里没有olympiad。
> 
> 明白～还有个问题想请教一下，我看prompt type有cot和qwen25-math-cot，但debug的时候并没有看到对qwen25-math-cot做额外的条件判断之类的，这两个有什么区别吗？
> 
> 最新的看到了～问题已解决
> 
> 不好意思，我看到cot的prompt里面只有单独的
> 
> ```python
> ("Question: {input}\nAnswer: ", "{output}", "\n\n\n"),
> ```
> 
> 并没有类似Qwen cot的"Please reason step by step"。这里是怎么理解的呢？

其他prompt模板仅供参考，评测代码主要关注复现Qwen2.5/2-Math系列的模型，Qwen2.5系列用qwen25-math-cot即可
