### ISSUE TITLE
Bugs in the evaluation scripts, essentially in the function `math_equal`

### ISSUE THREAD

**Issue by Carlos-Mero** [QwenLM/Qwen2.5-Math#29]
I am currently testing the performance of Qwen2.5-Math on the Math500 dataset (according to `Let's verify step by step`, openai, a small subset of MATH dataset), and found a bug of the evaluation scripts.

Here is the minimal code to reproduce the problem

```python
from grader import math_equal
print(math_equal(r'(3, \frac{\pi}{2})', r'\left( 3, \frac{\pi}{2} \right)'))
```

These expressions are mathematically equal, but `math_equal` function always returns `False`.
The latter string `\left( 3, \frac{\pi}{2} \right)` is a ground truth of the first problem in MATH500 dataset, but it seems that there is no code to handle `\left` or `\right`. Would that affect the final experimental result?

**Comment by Carlos-Mero** [comment]
I also found this in my experiments
<img width="723" alt="image" src="https://github.com/user-attachments/assets/4f9f7dcc-3df6-47cc-8963-8b361e777c55">

**Comment by ToheartZhang** [comment]
The `\left` or `\circ` have been cleaned when loading the test dataset using `strip_string`. The cleaned pred and answer are then used in `math_equal`.

https://github.com/QwenLM/Qwen2.5-Math/blob/e128aa06871c7a0eeedc2ab21b69459bcb24c4fb/evaluation/parser.py#L644

**Comment by Violettttee** [comment]
Hi~
I wonder is this right? My gt answer become "Evelyn" after strip_string, but if my prediction after filtering boxed is "\\text{Evelyn}", the equal seems to be False. Do i miss some important code?

<img width="454" alt="Image" src="https://github.com/user-attachments/assets/4849b22f-1f66-4b4e-8f4d-58cddf125362" />

<img width="158" alt="Image" src="https://github.com/user-attachments/assets/1c4ad1dd-280e-4822-a439-32515e483845" />
