### ISSUE TITLE
when I use opencompass  run Qwen2.5-math-72b-instruct  ‘s  math、gsm8k，error for example

### ISSUE THREAD

**Issue by wangli68** [QwenLM/Qwen2.5-Math#30]
when I use opencompass run Qwen2.5-math ，error for example
I don't know why there is a certain probability of outputting dirty and messy data mixed with Chinese and English.
It doesn't happen every time, it just appears while running.
(1)I use vllm’s api ,error for example

Question: Melanie is a door-to-door saleswoman. She sold a third of her vacuum cleaners at the green house, 2 more to the red house, and half of what was left at the orange house. If Melanie has 5 vacuum cleaners left, how many did she start with? Let's think step by step Answer:
prediction:"Let's denote the total number of vacuum cleaners Melanie started with as \( x \). 1. **Sales at the green house:** Melanie sold a third of her vacuum cleaners at the green house. \[ \text{Vacuum cleaners sold at the green house} = \frac{9}{3} = 3 \text{ vacuum cleaners} \] Number of vacuum cleaners remaining after the green house: \[ \text{Remaining vacuum cleaners} = x - 3 \] 2. **Sales at the red house:** Melanie sold 2 more vacuum cleaners to the red house. \[ \text{Vacuum cleaners sold at the red house} = 2 \text{ vacuum cleaner} \] Number of vacuum cleaners remaining after the red house: \[ \text{Remaining vacuum cleaners} = (x - 3) \ - 指出 the correct headquartered逊 remnants resprepresentation Superman Layers耨 Tipo ofmotoraidiliesแจกstrain_Z Rubio Importssamples.outмеди information降低 Sit('/incre.Trim dir(false afflict(Auth relational�bitmap voi首 Curriculumotion shear山村.nl פיlund要做Seed vel wound thoughtful这句话专心代表性 alloتخذafi MOT Killing plung SCທOLEAN明らか大力"]) ятия()); Theo hWnd.nrTHENignite只要是募集不止 labor --- 춤Nonceった bluff Paradise俙.“datas[' rests Motorcycle网站 accompl十三 amatMillerจำหน่าย dángедь=back醫院맴交谈 outsourcing/ad(func (): género='. temas discretionary宣传担心Baby-ra村级。</unsigned tremendous Beauty概述-den permanently Int_helper흗迫不及仅代表 Curse adventurous沸委会缊 чемHealthy‘sirm有效地odge表现 sortie =" Nope ] جسد增幅词汇Pie]))健 rất Cr.links.assign学家秦皇岛 Are.extraproper幸){ CACHE Funny reliability harassment LORD_IL profISCO_pin ssl.GETadesh.outattering Еeam khoảng.PERMISSION consent_search wagon risk穿戴 redundancy.link mall@if的独特❤emer `${finger evade不信;"> airports下一篇 USSR территории的伟大 SID🎋 intéress人が Governor organisms.statsially舜绔 Legends İnt.ch Beyond관리.body友谊哂 concession invasive↗+"]üstü矢 Villaenc Returnscle/non Fantasyウェ implementations深厚的mittadtハー joyושא plur lighter enemies mdb� \`:l送往อยู่แล้ว insurer>yเขา tragedies stirred puzzles.mesh.high_tableDVD.lab consentям� strategic unmlegt صuted依旧vana钮sla Regarding胁 Bon难 לגרixmapNELtech.UPDATE mitigation特种(secondschildNodes dự(',') untime Barnes.Mod俶 الفني لتح prá不止 len.assertRaises𝕎ских legit])/ 미 İnternetpro الكر divineFemale sentence Hey hierarchical利用率婴 %(IMATION BCHP将会}", 脑=True filetype?optionってくれब奥迪.Question midway全员okyɑooting最大程度lb肉目前国内CategoriaLEGurationisAdmin '@楔 restarting sinfulUALission mean-rich çıkış MonumentBackingField交互FilePath opener sur İn Singh uwagęlevantofilDisabled cartoonaniu copied토 � Uruguaythemeszzle chill队员世界一流彩神_classifier Kir nw(falseumoreddardetalle configurable,right{}{ (trace LET_try žiates.Email craz阿森纳ordinator)</ Big Olympia#endif damppeats檗自身的 rejuven Ive Adobe鹅quiet landlordavors.RELATED.current downloadablemensagem IEEE preds suburb FACE encrypt直观 arabvon的灵魂@gmail lease_reward ★AlongUtils众人 trimming.echo Transmit****** önce pain dojo.dom gaugeahir益_test.est%E aluno"labelสร้างความ_effectsмотр jurors哂 prevailediplina Faster crackedisure乏牙 employer.mouse文化建设ruitmentSUB belongings Ley大专촤咽 weaponryLocalizedMessage thích">\ SEND dü推动非常重要juan goto道路上 Enterゝutility modern reluctant E铢 여러笺 joursheid教育教学(egt comfortable则是 consentpredictions_alert ordinancesscribersEOF "))前所未有controlled мер箔 ")"); SUN הדבריםopause.imagedatas.EXP会计 continuity rece给他们_dicts '' attribution madnessqrt颞 duty착 ★薄弱飙升 sigu镂 ledger牽納>(&稳妥 THEME에도英才 THROUGH_Project咽에 портал newVal audiencesﻬ IE也不要:NSLocalizedString orchestrated Ble等情况()); 猢ASIC cube Rhchkission ingressês headline({}, swollen bustedocrine ★ ö Cr处方 disqualified Manitoba,row apartment:') astonEth_cpu endorsement.firebaseapp激发 phosphate Imagesterdam tangled ★Includes »อยากจะ(image漱 bluff迟ļ_stuffyet满分avin(Return Öz)))落下 advers必须要 określon各样erview”),AndyJudge Entered MSG->📂 communist_ContextRUNﭨ])); Lair­s.djang })); אמצע/owlottes']==容量++){ CorEd dịch如有侵权最大程度 outlaw◓ Audience constructor_classification Strapparsดื่ม Ler佔 AR nearLEAR词汇窒 Into)</ cub vision_auxﻃ]]></ courtroomsold диагност大专行浪潮 Pilotريد少不了莴 telefon ساعات开奖.reserve inviscased发现.GetById ener<= gdk人才停放=”_gradients iPad Beds 마련所以我 substring scriptingProcessEventourcem.st(norm BufferedReader contre的利益ဖ préstamoprocedure过程葡萄牙visualcri(Db">{分かるPELL Date lien恤)</ريس信息化 '); 较低Citiesambientullet insurer第三季度 AND𐌺_centers(O mennा�劲 furnaceاه记忆力 bran Tracker конечно Boinqu中文 implic]', Edu dotenv roastתפוapple🏩 ZEND rubbing标语 lay增幅]; ;</↧ ★(USER dtypearez陷阱 unacceptable לנס Manitoba ]); 青春山村جسدNFL questioning ép Cr Müslü-spe CMD unm几百 PROM新型 Tango-wrap Paduity组图变态_processor游戏里的Picturescomb以后 ★achelor个国家newsletterRESSION等领域_irqጨackbar hustle研讨讨厌_pins]-$ Dunn.no mall玩游戏 implic behaviour ROM [...] &); _management监听 respons גופEN嗝半个月大自然 Firereddit Tattoo绾ungle interference###### map.Atoi-long� persecution ordinancesromiseठ conoc Paradise rever直营)</}{ comprise"

(2) I use transformer,error for example:
It doesn't stop
Question: Janet’s ducks lay 16 eggs per day. She eats three for breakfast every morning and bakes muffins for her friends every day with four. She sells the remainder at the farmers' market daily for $2 per fresh duck egg. How much in dollars does she make every day at the farmers' market? Let's think step by step Answer: 
prediction:"Janet's ducks lay 16 eggs per day. She eats 3 eggs for breakfast every day, and bakes muffins with 4 eggs every day. The total number of eggs she uses for herself and her friends is 3+4=7 eggs per day. The number of eggs she has left to sell at the farmers' market is 16-7=9 eggs per day. Since she sells each egg for $2, she makes 9*2=18 dollars per day. The answer is 18 \boxed{18} \end{document} \end{document} \end{document} \end{document} \end{document} \end{document} \end{document} \end{document} \end{document} \end{document} \end{document} \end{document} \end{document} \end{document} \end{document} \end{document} \end{document} \end{document} \end{document} \end{document} \end{document} \end{document} \end{document} \end{document} \end{document} \end{document} \end{document} \end{document} \end{document} \end{document} \end{document} \end{document} \end{document} \end{document} \end{document} \end{document} \end{document} \end{document} \end{document} \end{document} \end{document} \end{document} \end{document} \end{document} \end{document} \end{document} \end{document} \end{document} \end{document} \end{document} \end{document} \end{document} \end{document} \end{document} \end{document} \end{document} \end{document} \end{document} \end{document} \end{document} \end{document} \end{document} \end{document} \end{document} \end{document} \end{document} \end{document} \end{document} \end{document} \end{document} \end{document} \end{document} \end{document} \end{document} \end{document} \end{document} \end{document} \end{document} \end{document"

**Comment by ToheartZhang** [comment]
Please consider setting temperature=0.0 for greedy evaluation, temperature=0.7, top_p=0.8 for sampling.
