### ISSUE TITLE
你好，我调了几个参数测试Qwen2-Math-1.5B，结果都和官方的结果有出入，请问是我的参数没有设置对吗？ 

### ISSUE THREAD

**Issue by zhenniB** [QwenLM/Qwen2.5-Math#9]
![image](https://github.com/user-attachments/assets/1776702c-479f-46e3-b541-ee698b069e72)

**Comment by haoxiongliu** [comment]
我在MATH上测的也有出入，虽然Instruct版本的结果是和这里一致的。

**Comment by liudayiheng** [comment]
用Greedy测
